# Generated by Django 5.0.4 on 2026-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsubmission',
            name='file_url',
            field=models.URLField(blank=True, help_text='MinIO/Drive URL', max_length=1000),
        ),
    ]
