# Generated by Django 5.0.4 on 2026-04-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_comment', 'New Comment'), ('task_due', 'Task Due'), ('file_uploaded', 'File Uploaded'), ('approval_requested', 'Approval Requested'), ('approval_done', 'Approval Done'), ('job_created', 'Job Created'), ('job_updated', 'Job Updated'), ('mention', 'Mention'), ('system', 'System'), ('general', 'General'), ('quality_review', 'Quality Review'), ('design_approved', 'Design Approved'), ('design_rejected', 'Design Rejected'), ('stock_alert', 'Low Stock Alert'), ('invoice_paid', 'Invoice Paid')], default='system', max_length=30),
        ),
    ]
