from django.urls import path
from . import views

urlpatterns = [
    path("boards/", views.BoardListCreateView.as_view(), name="boards"),
    path("boards/<uuid:pk>/", views.BoardDetailView.as_view(), name="board_detail"),
    path("boards/<uuid:board_id>/columns/", views.ColumnListCreateView.as_view(), name="columns"),
    path("boards/<uuid:board_id>/automations/", views.BoardAutomationListCreateView.as_view(), name="board_automations"),
    path("boards/<uuid:board_id>/custom-fields/", views.BoardCustomFieldListCreateView.as_view(), name="board_custom_fields"),
    path("custom-fields/<uuid:pk>/", views.BoardCustomFieldDetailView.as_view(), name="custom_field_detail"),
    path("boards/<uuid:board_id>/sprints/", views.SprintListCreateView.as_view(), name="board_sprints"),
    path("sprints/<uuid:pk>/", views.SprintDetailView.as_view(), name="sprint_detail"),
    path("columns/<uuid:pk>/", views.ColumnDetailView.as_view(), name="column_detail"),
    path("automations/<uuid:pk>/", views.BoardAutomationDetailView.as_view(), name="automation_detail"),
    path("tasks/", views.TaskListCreateView.as_view(), name="tasks"),
    path("tasks/bulk-action/", views.TaskBulkActionView.as_view(), name="task_bulk_action"),
    path("tasks/archived/", views.ArchivedTaskListView.as_view(), name="tasks_archived"),
    path("tasks/workload/", views.WorkloadView.as_view(), name="workload"),
    path("tasks/<uuid:pk>/", views.TaskDetailView.as_view(), name="task_detail"),
    path("tasks/<uuid:pk>/move/", views.TaskMoveView.as_view(), name="task_move"),
    path("tasks/<uuid:pk>/timer/", views.TaskTimerToggleView.as_view(), name="task_timer"),
    path("tasks/<uuid:pk>/spawn-recurrence/", views.TaskSpawnRecurrenceView.as_view(), name="task_spawn_recurrence"),
    path("tasks/<uuid:task_id>/comments/", views.CommentListCreateView.as_view(), name="task_comments"),
    path("tasks/<uuid:task_id>/time-log/", views.TimeLogCreateView.as_view(), name="task_timelog"),
    path("tasks/<uuid:task_id>/attachments/", views.TaskAttachmentView.as_view(), name="task_attachments"),
    path("attachments/<uuid:pk>/", views.TaskAttachmentDeleteView.as_view(), name="attachment_delete"),
    path("comments/<uuid:pk>/", views.CommentDetailView.as_view(), name="comment_detail"),
    path("tags/", views.TagListCreateView.as_view(), name="tags"),
    path("admin-overview/", views.AdminBoardsOverviewView.as_view(), name="admin_overview"),
    path("tracker/", views.GlobalTaskTrackerView.as_view(), name="task_tracker"),
]
