# Generated by Django 6.0.3 on 2026-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
