# Generated by Django 6.0.3 on 2026-04-05 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_client_status_task_is_checked_task_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_value', models.CharField(blank=True, max_length=255)),
                ('actions', models.JSONField(default=list)),
                ('label_text', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='tasks.board')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
