# Generated by Django 5.0.4 on 2026-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_blocked_by_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated Minutes'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
