# Generated by Django 5.0.4 on 2026-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_estimated_minutes_task_is_timer_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/%Y/%m/'),
        ),
    ]
