# Generated by Django 5.0.4 on 2026-05-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_origin_board'),
        ('tasks', '0009_sprint_fields'),
    ]

    operations = [
    ]
