# Generated by Django 5.0.4 on 2026-05-10 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_merge_0007_task_origin_board_0009_sprint_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_payload', models.JSONField(default=dict)),
                ('actions_executed', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.boardautomation')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
