# Generated by Django 5.0.4 on 2026-05-09 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A friendly label for this integration', max_length=200)),
                ('spreadsheet_id', models.CharField(help_text='Google Sheets ID (from the URL) or the full URL', max_length=500)),
                ('sheet_name', models.CharField(default='Sheet1', help_text='The tab/sheet name inside the spreadsheet', max_length=200)),
                ('header_row', models.PositiveSmallIntegerField(default=1, help_text='Which row contains the column headers (usually 1)')),
                ('column_mapping', models.JSONField(default=dict, help_text='Map CRM fields to sheet columns. Keys: name, email, phone, company, address, notes, website, type, stage. Values: column letter (A/B/C) or header name.')),
                ('sync_interval_minutes', models.PositiveSmallIntegerField(default=5, help_text='How often (in minutes) to check the sheet for new rows')),
                ('conflict_strategy', models.CharField(choices=[('skip', 'Skip — Ignore duplicate emails'), ('update', 'Update — Overwrite existing customer data')], default='skip', help_text='What to do when a customer with the same email already exists', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this integration')),
                ('default_customer_type', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer')], default='lead', max_length=15)),
                ('default_customer_stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=15)),
                ('last_synced_row', models.PositiveIntegerField(default=0, help_text='Index of the last sheet row that was successfully synced')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_sync_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
                ('default_assigned_to', models.ForeignKey(blank=True, help_text='Default user to assign imported customers to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Sheets Integration',
                'verbose_name_plural': 'Google Sheets Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('running', 'Running')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('manual', 'Manual')], default='scheduler', max_length=20)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.googlesheetsintegration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
