# Generated by Django 5.0.4 on 2026-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='drive_folder_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
