# Generated by Django 5.0.4 on 2026-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_options_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 10x15 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='finishing',
            field=models.TextField(blank=True, help_text='e.g. Matte Lamination, UV Spot, Die Cut'),
        ),
        migrations.AddField(
            model_name='job',
            name='paper_type',
            field=models.CharField(blank=True, help_text='e.g. Glossy 150g, Matte 300g', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='printing_colors',
            field=models.CharField(blank=True, help_text='e.g. CMYK, Pantone, B&W', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='product_type',
            field=models.CharField(blank=True, help_text='e.g. Sticker, Flyer, Box', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of copies/items'),
        ),
    ]
